//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Products_for_lists = new HashSet<Products_for_lists>();
        }
    
        public int Product_code { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Kod_Category { get; set; }
        public Nullable<int> Location_Kod { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_for_lists> Products_for_lists { get; set; }
    }
}
