//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserved_lists
    {
        public int List_code { get; set; }
        public string User_Kod { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name_List { get; set; }
    }
}
