//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EazyShopEntities : DbContext
    {
        public EazyShopEntities()
            : base("name=EazyShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reserved_lists> Reserved_lists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
