//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> Column_number { get; set; }
        public Nullable<int> line_number { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public Nullable<int> Shelf_number { get; set; }
    }
}
