//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_Code { get; set; }
        public string First_name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Password { get; set; }
        public string Reserved_lists { get; set; }
    }
}
